### PR TITLE
Send SMS when bids gets created, updated and deleted

### PR DESCRIPTION
**Pull request by nagarajankannan**
**Changes Proposed**
- 

**_Middlewares Added:_**
- Middlewares like `verifyBuyer` and `verifySeller` are added to check whether the user ID that is set in `verifyToken` middleware is actually a buyer or seller respectively. (This middleware will be useful for validating the persona specific endpoints.)
- ~`verifyBid` middleware is added which ensures the bids can be deleted or updated only the buyer who created the bid. (Exception for admins).~
- `getSeller` and `getBuyer` middlewares are added which verifies the given sellerID or BuyerId is valid.
- These middleware are introduced as a part of this notification story because in service at various places we have to validate and fetch the users so doing it as a part of middleware to avoid repetition. Now the user model will be stored in the request object before handing it over to the service.

~**_Endpoints Updated:_**~
~- `PUT /bids/:bidId` endpoint is updated to `PUT buyer/:buyerId/bids/:bidId`~
~- `DELETE /bids/:bidId` endpoint is updated to `DELETE buyer/:buyerId/bids/:bidId`~
~- The above change is introduced to safeguard bids so that it restricts users to update or delete only the bids that they created. (Exception for admins)~

### CODE REVIEW

**Comment by nagarajankannan** [comment]
> The `buyer` and `seller` refer to domain objects, whereas the `verifyBid` denotes a verb/action. Can we please stick to the same convention?

Done 👍

**Comment by nagarajankannan** [comment]
- As the `PUT /bids/:bidId` endpoint is currently used by both sellers. Reverted (`buyer/:buyerId/bids/:bidId`) endpoint changes. Same applies for `DELETE` endpoint as well.
- Updated `verifyToken` middleware to include persona in the JWT which is used in `middleware/bid.js`.
- Send SMS notification for `approved` and `denied` status.

**Comment by vraravam** [comment]
LGTM!

**Comment by vraravam** [comment]
@nagarajankannan - before this gets merged into the `master` branch - please rebase and squash the commits into a single one.

**Pull request merged**
