### PR TITLE
[Vijay] Introducing support for migrations using 'sequelize'. Seeding…

### PR DESCRIPTION
**Pull request by vraravam**
… is done (but, not yet randomized).

### CODE REVIEW

**Comment by nagarajankannan** [comment]
@vraravam We should have a plan to skip the table creation migrations in production. We can either have environment checks or insert those files names into `SequelizeMeta` table. so that no accidental migration runs happen.

 Other than that code looks good to me.

**Comment by vraravam** [comment]
I was going to ask Azhagu if the data in the current db can be blasted away - since it most likely contains test data. In which case, we can run this code (including the migrations) to start from a clean db.

**Comment by vraravam** [comment]
Irrespective of the answer to the above, I'm going to run the sql commands to create and populate the `SequelizeMeta` table now in the hosted env. That way, even if we recreate it from scratch, nothing is lost. And if we don't, then this manual step will cover the case of the next deployment.

**Comment by vraravam** [comment]
For reference, these are the sql commands that i ran:
```
CREATE TABLE public."SequelizeMeta" (
    name character varying(255) NOT NULL
);

ALTER TABLE ONLY public."SequelizeMeta"
    ADD CONSTRAINT "SequelizeMeta_pkey" PRIMARY KEY (name);

INSERT INTO public."SequelizeMeta"(name) values('20190803161504-create-user_details-table.js');
INSERT INTO public."SequelizeMeta"(name) values('20190803161589-create-user_otp-table.js');
INSERT INTO public."SequelizeMeta"(name) values('20190803163529-create-items-table.js');
INSERT INTO public."SequelizeMeta"(name) values('20190803163704-create-bids-table.js');
```

**Pull request merged**
