### PR TITLE
Setup dev environment using docker-compose

### PR DESCRIPTION
**Pull request by arunvelsriram**
- Use docker-compose to start the dependencies like frontend and postgres database using docker-compose
- Update readme with dev machine setup instructions

### CODE REVIEW

**Comment by arunvelsriram** [comment]
This PR and https://github.com/chennaitricolor/wastexchange-fe/pull/7 are dependent on each other so both need to be merged at the same time.

**Comment by arunvelsriram** [comment]
@vraravam to make frontend dev machine setup work we have to allow configuring development DB connection variables through environment variables: https://github.com/chennaitricolor/wastexchange-be/blob/master/src/config/database.json#L6.

**Comment by vraravam** [comment]
@arunvelsriram - can you please also incorporate the migrations command into the Dockerfile?

**Comment by arunvelsriram** [comment]
> @vraravam to make frontend dev machine setup work we have to allow configuring development DB connection variables through environment variables: https://github.com/chennaitricolor/wastexchange-be/blob/master/src/config/database.json#L6.

I have made this change as well

**Comment by arunvelsriram** [comment]
> @arunvelsriram - can you please also incorporate the migrations command into the Dockerfile?

Migrations now run before starting the app

**Comment by arunvelsriram** [comment]
this is ready to be merged.

**Pull request merged**
