### PR TITLE
[Vijay] Spoof the OTP to be the mobile number if not in 'production' …

### PR DESCRIPTION
**Pull request by vraravam**
…env.

@VenkteshV , @nagarajankannan - please review and approve the PR quickly. This is blocking the mobile devs working on the registration logic.

### CODE REVIEW

**Comment by arunvelsriram** [comment]
We are using `ENV=production` for staging here https://github.com/chennaitricolor/wastexchange-be/blob/master/deployment/group_vars/staging/vars.yaml#L3

Can we use a separate env variable for spoofing SMS?

There are only 2 envs with respect to code: development and production. Either we have to introduce staging or use a different variable.

**Comment by vraravam** [comment]
@arunvelsriram - "staging" != "production" - please change that line in vars.yaml.

**Comment by arunvelsriram** [comment]
In database config, we will have to introduce staging as well.

**Comment by vraravam** [comment]
yes - when we introduce a new env, we will have to do all that ;)

**Comment by vraravam** [comment]
@VenkteshV - whats the difference between `NODE_ENV` and `NODE_CONFIG_ENV`?

**Pull request merged**
